// Database configuration
// In production, use PostgreSQL with Prisma or TypeORM
// For development, we'll use a mock database structure

import bcrypt from "bcryptjs";
import type {
  AuditLogEntry,
  ChatMessage,
  ChatPublicKey,
  ChatReport,
  ChatRoom,
  ChatRoomRead,
  ChatUserBlock,
  Document,
  InviteCode,
  MarketplaceItem,
  Notification,
  VerificationRequest,
} from "@/types";

export const DATABASE_URL = process.env.DATABASE_URL || "postgresql://user:password@localhost:5432/imperiu_sui_luris";

// Mock database for development
export const mockDatabase = {
  users: [
    {
      id: "user_001",
      email: "citizen@imperiu-sui-luris.com",
      username: "citizen_test",
      fullName: "Test Citizen",
      country: "Romania",
      role: "user",
      badge: "citizen",
      accountStatus: "active",
      isVerified: true,
      // default dev password: 'password123' (hashed)
      passwordHash: bcrypt.hashSync("password123", 8),
      citizenship: "active",
      totalLandArea: 2500,
      totalFunds: 5000,
      documentCount: 3,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date(),
    },
    {
      id: "user_002",
      email: "maria.popescu@imperiu-sui-luris.com",
      username: "maria_popescu",
      fullName: "Maria Popescu",
      country: "Romania",
      role: "user",
      badge: "citizen",
      accountStatus: "active",
      isVerified: false,
      passwordHash: bcrypt.hashSync("password123", 8),
      citizenship: "active",
      totalLandArea: 0,
      totalFunds: 120,
      documentCount: 0,
      createdAt: new Date("2024-02-10"),
      updatedAt: new Date(),
    },
    {
      id: "user_003",
      email: "alex.stefan@imperiu-sui-luris.com",
      username: "alex_stefan",
      fullName: "Alex Ștefan",
      country: "Romania",
      role: "user",
      badge: "citizen",
      accountStatus: "active",
      passwordHash: bcrypt.hashSync("password123", 8),
      isVerified: false,
      citizenship: "pending",
      totalLandArea: 0,
      totalFunds: 0,
      documentCount: 0,
      createdAt: new Date("2024-03-05"),
      updatedAt: new Date(),
    },
    {
      id: "user_004",
      email: "ion.ionescu@imperiu-sui-luris.com",
      username: "ion_ionescu",
      fullName: "Ion Ionescu",
      country: "Romania",
      role: "user",
      badge: "citizen",
      accountStatus: "active",
      isVerified: false,
      passwordHash: bcrypt.hashSync("password123", 8),
      citizenship: "active",
      totalLandArea: 750,
      totalFunds: 980,
      documentCount: 1,
      createdAt: new Date("2024-03-20"),
      updatedAt: new Date(),
    },
    {
      id: "user_admin",
      email: "admin@imperiu-sui-luris.com",
      username: "admin_sui",
      fullName: "State Administrator",
      country: "Imperiul Sui Juris",
      citizenship: "active",
      role: "admin",
      badge: "president",
      accountStatus: "active",
      isVerified: true,
      passwordHash: bcrypt.hashSync(process.env.ADMIN_PASSWORD || "test1", 8),
      createdAt: new Date("2023-01-01"),
      updatedAt: new Date(),
    },
  ],
  documents: [
    {
      id: "doc_001",
      userId: "user_001",
      type: "bulletin",
      documentNumber: "ISL-2024-001-A",
      issueDate: new Date("2024-01-15"),
      price: 10,
      status: "active",
      createdAt: new Date("2024-01-15"),
      updatedAt: new Date(),
    },
    {
      id: "doc_002",
      userId: "user_001",
      type: "passport",
      documentNumber: "ISL-2024-001-B",
      issueDate: new Date("2024-02-01"),
      expiryDate: new Date("2034-02-01"),
      price: 50,
      status: "active",
      createdAt: new Date("2024-02-01"),
      updatedAt: new Date(),
    },
    // Admin documents (all 4 types for testing)
    {
      id: "doc_admin_001",
      userId: "user_admin",
      type: "bulletin",
      documentNumber: "ISL-ADMIN-2023-001",
      verificationCode: "ADMIN-0001-BULL",
      issueDate: new Date("2023-01-01"),
      expiryDate: new Date("2033-01-01"),
      photoUrl: "https://i.pravatar.cc/400?img=12",
      price: 0,
      status: "active",
      createdAt: new Date("2023-01-01"),
      updatedAt: new Date(),
    },
    {
      id: "doc_admin_002",
      userId: "user_admin",
      type: "passport",
      documentNumber: "ISL-ADMIN-2023-002",
      verificationCode: "ADMIN-0002-PASS",
      issueDate: new Date("2023-01-01"),
      expiryDate: new Date("2033-01-01"),
      photoUrl: "https://i.pravatar.cc/400?img=12",
      price: 0,
      status: "active",
      createdAt: new Date("2023-01-01"),
      updatedAt: new Date(),
    },
    {
      id: "doc_admin_003",
      userId: "user_admin",
      type: "certificate",
      documentNumber: "ISL-ADMIN-2023-003",
      verificationCode: "ADMIN-0003-CERT",
      issueDate: new Date("2023-01-01"),
      expiryDate: new Date("2024-01-01"),
      price: 0,
      status: "active",
      createdAt: new Date("2023-01-01"),
      updatedAt: new Date(),
    },
    {
      id: "doc_admin_004",
      userId: "user_admin",
      type: "visitor_certificate",
      documentNumber: "ISL-ADMIN-2023-004",
      verificationCode: "ADMIN-0004-VCRT",
      issueDate: new Date("2023-01-01"),
      expiryDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000), // 3 months from now
      photoUrl: "https://i.pravatar.cc/400?img=12",
      price: 0,
      status: "active",
      createdAt: new Date("2023-01-01"),
      updatedAt: new Date(),
    },
  ] as Document[],
  chatRooms: [] as ChatRoom[],
  chatMessages: [] as ChatMessage[],
  chatReads: [] as ChatRoomRead[],
  chatPublicKeys: [] as ChatPublicKey[],
  chatUserBlocks: [] as ChatUserBlock[],
  chatReports: [] as ChatReport[],
  verificationRequests: [] as VerificationRequest[],
  auditLogs: [] as AuditLogEntry[],
  notifications: [] as Notification[],
  // Seed invite for initial onboarding/testing (single-use per runtime)
  invites: [
    {
      code: "ISL-START2025",
      inviterUserId: "user_admin",
      createdAt: new Date("2025-12-29"),
    },
  ] as InviteCode[],
  landProperties: [
    {
      id: "land_001",
      userId: "user_001",
      name: "Green Valley Farm",
      location: "North Sector, Imperiul Sui Juris",
      coordinates: {
        latitude: 45.9432,
        longitude: 24.9668,
      },
      areaSize: 2500,
      type: "agricultural",
      resources: ["river access", "fertile soil"],
      purchaseDate: new Date("2024-03-01"),
      purchasePrice: 500,
      description: "Beautiful agricultural land with river access for sustainable farming",
      images: [],
      status: "active",
      createdAt: new Date("2024-03-01"),
      updatedAt: new Date(),
    },
  ],
  marketplaceItems: [
    {
      id: "item_001",
      type: "document",
      name: "State Bulletin",
      description: "Official bulletin of Imperiul Sui Juris - proof of citizenship",
      price: 10,
      currency: "credits",
      documentType: "bulletin",
      availability: 999,
      createdBy: "user_admin",
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date(),
    },
    {
      id: "item_002",
      type: "document",
      name: "State Passport",
      description: "Official passport for citizens of Imperiul Sui Juris - valid for 10 years",
      price: 50,
      currency: "credits",
      documentType: "passport",
      availability: 999,
      createdBy: "user_admin",
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date(),
    },
    {
      id: "item_003",
      type: "resource",
      name: "Pure Silver Ingot",
      description: "High-purity silver ingot (100g) from state reserves",
      price: 100,
      currency: "credits",
      metalType: "silver",
      quantity: 1,
      availability: 500,
      createdBy: "user_admin",
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date(),
    },
    {
      id: "item_004",
      type: "resource",
      name: "Pure Gold Ingot",
      description: "High-purity gold ingot (50g) from state reserves",
      price: 500,
      currency: "credits",
      metalType: "gold",
      quantity: 1,
      availability: 100,
      createdBy: "user_admin",
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date(),
    },
    {
      id: "item_005",
      type: "resource",
      name: "Diamond",
      description: "Certified diamond (1 carat) from state mines",
      price: 1000,
      currency: "credits",
      metalType: "diamond",
      quantity: 1,
      availability: 50,
      createdBy: "user_admin",
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date(),
    },
    {
      id: "item_006",
      type: "land",
      name: "Teren - Zona Centrală",
      description: "Teren disponibil pentru alocare în zonă centrală.",
      price: 250,
      currency: "credits",
      landZone: "Central",
      landAreaSize: 1000,
      landType: "mixed",
      availability: 10,
      createdBy: "user_admin",
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date(),
    },
  ] as MarketplaceItem[],
  transactions: [] as unknown[],
  feedPosts: [
    {
      id: "feed_001",
      authorId: "user_admin",
      content: "Welcome to Imperiul Sui Juris! We're building a new nation focused on liberty, brotherhood, and sustainability. Join our mission to protect water, ensure food security, and develop clean energy!",
      images: [],
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date(),
      likes: 42,
      comments: [],
    },
  ],
};
