// Database configuration
// In production, use PostgreSQL with Prisma or TypeORM
// For development, we'll use a mock database structure

import bcrypt from "bcryptjs";
import type { MarketplaceItem } from "@/types";

export const DATABASE_URL = process.env.DATABASE_URL || "postgresql://user:password@localhost:5432/imperiu_sui_luris";

// Mock database for development
export const mockDatabase = {
  users: [
    {
      id: "user_001",
      email: "citizen@imperiu-sui-luris.com",
      username: "citizen_test",
      fullName: "Test Citizen",
      country: "Romania",
      role: "user",
      badge: "citizen",
      // default dev password: 'password123' (hashed)
      passwordHash: bcrypt.hashSync("password123", 8),
      citizenship: "active",
      totalLandArea: 2500,
      totalFunds: 5000,
      documentCount: 3,
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date(),
    },
    {
      id: "user_admin",
      email: "admin@imperiu-sui-luris.com",
      username: "admin_sui",
      fullName: "State Administrator",
      country: "Imperiul Sui Luris",
      citizenship: "active",
      role: "admin",
      badge: "president",
      passwordHash: bcrypt.hashSync("adminpass", 8),
      createdAt: new Date("2023-01-01"),
      updatedAt: new Date(),
    },
  ],
  documents: [
    {
      id: "doc_001",
      userId: "user_001",
      type: "bulletin",
      documentNumber: "ISL-2024-001-A",
      issueDate: new Date("2024-01-15"),
      price: 10,
      status: "active",
      createdAt: new Date("2024-01-15"),
      updatedAt: new Date(),
    },
    {
      id: "doc_002",
      userId: "user_001",
      type: "passport",
      documentNumber: "ISL-2024-001-B",
      issueDate: new Date("2024-02-01"),
      expiryDate: new Date("2034-02-01"),
      price: 50,
      status: "active",
      createdAt: new Date("2024-02-01"),
      updatedAt: new Date(),
    },
  ],
  landProperties: [
    {
      id: "land_001",
      userId: "user_001",
      name: "Green Valley Farm",
      location: "North Sector, Imperiul Sui Luris",
      coordinates: {
        latitude: 45.9432,
        longitude: 24.9668,
      },
      areaSize: 2500,
      type: "agricultural",
      resources: ["river access", "fertile soil"],
      purchaseDate: new Date("2024-03-01"),
      purchasePrice: 500,
      description: "Beautiful agricultural land with river access for sustainable farming",
      images: [],
      status: "active",
      createdAt: new Date("2024-03-01"),
      updatedAt: new Date(),
    },
  ],
  marketplaceItems: [
    {
      id: "item_001",
      type: "document",
      name: "State Bulletin",
      description: "Official bulletin of Imperiul Sui Luris - proof of citizenship",
      price: 10,
      currency: "credits",
      documentType: "bulletin",
      availability: 999,
      createdBy: "user_admin",
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date(),
    },
    {
      id: "item_002",
      type: "document",
      name: "State Passport",
      description: "Official passport for citizens of Imperiul Sui Luris - valid for 10 years",
      price: 50,
      currency: "credits",
      documentType: "passport",
      availability: 999,
      createdBy: "user_admin",
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date(),
    },
    {
      id: "item_003",
      type: "resource",
      name: "Pure Silver Ingot",
      description: "High-purity silver ingot (100g) from state reserves",
      price: 100,
      currency: "credits",
      metalType: "silver",
      quantity: 1,
      availability: 500,
      createdBy: "user_admin",
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date(),
    },
    {
      id: "item_004",
      type: "resource",
      name: "Pure Gold Ingot",
      description: "High-purity gold ingot (50g) from state reserves",
      price: 500,
      currency: "credits",
      metalType: "gold",
      quantity: 1,
      availability: 100,
      createdBy: "user_admin",
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date(),
    },
    {
      id: "item_005",
      type: "resource",
      name: "Diamond",
      description: "Certified diamond (1 carat) from state mines",
      price: 1000,
      currency: "credits",
      metalType: "diamond",
      quantity: 1,
      availability: 50,
      createdBy: "user_admin",
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date(),
    },
    {
      id: "item_006",
      type: "land",
      name: "Teren - Zona Centrală",
      description: "Teren disponibil pentru alocare în zonă centrală.",
      price: 250,
      currency: "credits",
      landZone: "Central",
      landAreaSize: 1000,
      landType: "mixed",
      availability: 10,
      createdBy: "user_admin",
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date(),
    },
  ] as MarketplaceItem[],
  transactions: [] as unknown[],
  feedPosts: [
    {
      id: "feed_001",
      authorId: "user_admin",
      content: "Welcome to Imperiul Sui Luris! We're building a new nation focused on liberty, brotherhood, and sustainability. Join our mission to protect water, ensure food security, and develop clean energy!",
      images: [],
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date(),
      likes: 42,
      comments: [],
    },
  ],
};
